import { GridParcel } from "@/types/parcel";

export const INITIAL_PARCELS: GridParcel[] = [
  {
    id: "p-001",
    grid_id: "US-VA-LOUD-10KM-0104",
    state_code: "VA",
    county_name: "Loudoun",
    area_sq_km: 10.0,
    lon: -77.534,
    lat: 39.043,
    power_distance_miles: 0.8,
    substation_distance_miles: 1.4,
    substation_voltage_kv: 500,
    substation_name: "Pleasant View 500kV",
    grid_operator: "PJM",
    groundwater_depth_ft: 34.2,
    water_availability_index: 92.5,
    seismic_hazard_pga: 0.032,
    flood_risk_score: 12.0,
    hurricane_risk_score: 18.5,
    cooling_degree_days: 980.0,
    ambient_avg_temp_f: 55.4,
    free_cooling_potential_hours: 4820,
    power_score: 96.0,
    water_score: 92.5,
    risk_score: 89.0,
    climate_score: 84.0,
    composite_score: 91.8,
    cluster_zone_id: 1,
    cluster_label: "Prime Zone A (40 km² Hyper-Cluster)",
    is_prime_zone: true,
    megawatt_capacity_estimate: 600,
  },
  {
    id: "p-002",
    grid_id: "US-VA-LOUD-10KM-0105",
    state_code: "VA",
    county_name: "Loudoun",
    area_sq_km: 10.0,
    lon: -77.498,
    lat: 39.042,
    power_distance_miles: 1.1,
    substation_distance_miles: 1.9,
    substation_voltage_kv: 500,
    substation_name: "Goose Creek 500kV",
    grid_operator: "PJM",
    groundwater_depth_ft: 38.0,
    water_availability_index: 89.0,
    seismic_hazard_pga: 0.035,
    flood_risk_score: 15.0,
    hurricane_risk_score: 19.0,
    cooling_degree_days: 995.0,
    ambient_avg_temp_f: 55.8,
    free_cooling_potential_hours: 4760,
    power_score: 93.5,
    water_score: 89.0,
    risk_score: 87.5,
    climate_score: 83.0,
    composite_score: 89.6,
    cluster_zone_id: 1,
    cluster_label: "Prime Zone A (40 km² Hyper-Cluster)",
    is_prime_zone: true,
    megawatt_capacity_estimate: 600,
  },
  {
    id: "p-003",
    grid_id: "US-VA-PRIN-10KM-0210",
    state_code: "VA",
    county_name: "Prince William",
    area_sq_km: 10.0,
    lon: -77.580,
    lat: 38.830,
    power_distance_miles: 1.4,
    substation_distance_miles: 2.2,
    substation_voltage_kv: 500,
    substation_name: "Gainsville 500kV",
    grid_operator: "PJM",
    groundwater_depth_ft: 45.0,
    water_availability_index: 85.0,
    seismic_hazard_pga: 0.038,
    flood_risk_score: 18.0,
    hurricane_risk_score: 22.0,
    cooling_degree_days: 1040.0,
    ambient_avg_temp_f: 56.5,
    free_cooling_potential_hours: 4610,
    power_score: 91.0,
    water_score: 85.0,
    risk_score: 85.0,
    climate_score: 80.0,
    composite_score: 86.6,
    cluster_zone_id: 2,
    cluster_label: "Prime Zone B (30 km² Corridor)",
    is_prime_zone: true,
    megawatt_capacity_estimate: 450,
  },
  {
    id: "p-004",
    grid_id: "US-VA-PRIN-10KM-0211",
    state_code: "VA",
    county_name: "Prince William",
    area_sq_km: 10.0,
    lon: -77.545,
    lat: 38.828,
    power_distance_miles: 2.0,
    substation_distance_miles: 3.1,
    substation_voltage_kv: 230,
    substation_name: "Manassas 230kV",
    grid_operator: "PJM",
    groundwater_depth_ft: 52.0,
    water_availability_index: 81.0,
    seismic_hazard_pga: 0.040,
    flood_risk_score: 20.0,
    hurricane_risk_score: 24.0,
    cooling_degree_days: 1060.0,
    ambient_avg_temp_f: 56.8,
    free_cooling_potential_hours: 4550,
    power_score: 84.0,
    water_score: 81.0,
    risk_score: 82.0,
    climate_score: 78.0,
    composite_score: 82.0,
    cluster_zone_id: 2,
    cluster_label: "Prime Zone B (30 km² Corridor)",
    is_prime_zone: true,
    megawatt_capacity_estimate: 450,
  },
  {
    id: "p-005",
    grid_id: "US-VA-FAUQ-10KM-0312",
    state_code: "VA",
    county_name: "Fauquier",
    area_sq_km: 10.0,
    lon: -77.720,
    lat: 38.710,
    power_distance_miles: 3.5,
    substation_distance_miles: 5.2,
    substation_voltage_kv: 230,
    substation_name: "Warrenton East 230kV",
    grid_operator: "PJM",
    groundwater_depth_ft: 68.0,
    water_availability_index: 74.0,
    seismic_hazard_pga: 0.045,
    flood_risk_score: 14.0,
    hurricane_risk_score: 20.0,
    cooling_degree_days: 1020.0,
    ambient_avg_temp_f: 56.0,
    free_cooling_potential_hours: 4680,
    power_score: 75.0,
    water_score: 74.0,
    risk_score: 86.0,
    climate_score: 81.0,
    composite_score: 77.8,
    cluster_zone_id: -1,
    cluster_label: "Unclustered / Secondary Candidate",
    is_prime_zone: false,
    megawatt_capacity_estimate: 150,
  },
  {
    id: "p-006",
    grid_id: "US-VA-FAUQ-10KM-0313",
    state_code: "VA",
    county_name: "Fauquier",
    area_sq_km: 10.0,
    lon: -77.780,
    lat: 38.680,
    power_distance_miles: 7.2,
    substation_distance_miles: 9.8,
    substation_voltage_kv: 115,
    substation_name: "Remington 115kV",
    grid_operator: "PJM",
    groundwater_depth_ft: 95.0,
    water_availability_index: 62.0,
    seismic_hazard_pga: 0.052,
    flood_risk_score: 28.0,
    hurricane_risk_score: 25.0,
    cooling_degree_days: 1050.0,
    ambient_avg_temp_f: 56.4,
    free_cooling_potential_hours: 4590,
    power_score: 52.0,
    water_score: 62.0,
    risk_score: 75.0,
    climate_score: 79.0,
    composite_score: 63.1,
    cluster_zone_id: -1,
    cluster_label: "Unclustered / Sub-optimal",
    is_prime_zone: false,
    megawatt_capacity_estimate: 100,
  }
];
